inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'gemfiles/*'
  NewCops: enable
  SuggestExtensions: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/ClassLength:
  Exclude:
    - 'test/*'

Style/Documentation:
  Enabled: false

