language: ruby
cache: bundler

notifications:
  email: false

services:
  - postgresql
  - mysql

before_install:
  - gem install bundler -v 2.0.2

before_script:
  - mysql -e 'create database i18n_unittest;'
  - psql -c 'create database i18n_unittest;' -U postgres

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7

gemfile:
  - gemfiles/Gemfile.rails_3
  - gemfiles/Gemfile.rails_4
  - gemfiles/Gemfile.rails_5
  - gemfiles/Gemfile.rails_6
  - gemfiles/Gemfile.rails_head

env:
  - PG_USER=postgres

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.3
      gemfile: gemfiles/Gemfile.rails_6
    - rvm: 2.4
      gemfile: gemfiles/Gemfile.rails_6
    - rvm: 2.3
      gemfile: gemfiles/Gemfile.rails_head
    - rvm: 2.4
      gemfile: gemfiles/Gemfile.rails_head
    - rvm: 2.5
      gemfile: gemfiles/Gemfile.rails_head
