name: CI Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: ['**']

jobs:
  test:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: i18n_unittest
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DB: i18n_unittest
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - '3306:3306'
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    strategy:
      fail-fast: true
      matrix:
        # os: [ubuntu-latest, macos-latest]
        # ruby: [2.3, 2.4, 2.5, 2.6, 2.7, 3.0, 'head']
        os: [ubuntu-latest]
        ruby: [2.7]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: |
          sudo /etc/init.d/mysql start
          bundle exec rake
