name: Tests
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test_sqlite:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          ### TEST ALL RUBY VERSIONS, USE DEFAULT GEMFILE
          - ruby: 2.3
          - ruby: 2.4
          - ruby: 2.5
          - ruby: 2.6
          - ruby: 2.7
          - ruby: 3.0

          ### RAILS VERSION TESTING
          - ruby: 2.6
            gemfile: gemfiles/rails-3.2.sqlite3
          - ruby: 2.6
            gemfile: gemfiles/rails-4.2.sqlite3
          - ruby: 2.6
            gemfile: gemfiles/rails-5.0.sqlite3
          - ruby: 2.6
            gemfile: gemfiles/rails-5.1.sqlite3
          - ruby: 2.6
            gemfile: gemfiles/rails-5.2.sqlite3
          - ruby: 2.6
            gemfile: gemfiles/rails-6.0.sqlite3
          - ruby: 2.6
            gemfile: gemfiles/rails-6.1.sqlite3
          - ruby: 2.6
            gemfile: gemfiles/rails-7.0.sqlite3

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"

    steps:
    - uses: actions/checkout@v2

    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"

    - name: Bundle
      run: |
        gem install bundler:1.17.3
        bundle _1.17.3_ install

    - name: Run tests
      run: |
        #bundle exec rake db:test:prepare
        bundle exec rake

  #test_mysql:
  #  runs-on: ubuntu-20.04
  #  services:
  #    mysql:
  #      image: mariadb
  #      env:
  #        MYSQL_ROOT_PASSWORD: password
  #        MYSQL_DATABASE: test
  #      options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
  #      ports: ['3306:3306']

  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      include:
  #        ### RAILS VERSION TESTING
  #        ### DONT WORRY ABOUT TESTING ALL RUBY VERSIONS. THIS IS COVERED IN THE SQLITE3 TESTS
  #        - ruby: 2.6
  #          gemfile: gemfiles/rails-3.2.mysql2
  #        - ruby: 2.6
  #          gemfile: gemfiles/rails-4.2.mysql2
  #        - ruby: 2.6
  #          gemfile: gemfiles/rails-5.0.mysql2
  #        - ruby: 2.6
  #          gemfile: gemfiles/rails-5.1.mysql2
  #        - ruby: 2.6
  #          gemfile: gemfiles/rails-5.2.mysql2
  #        - ruby: 2.6
  #          gemfile: gemfiles/rails-6.0.mysql2
  #        - ruby: 2.6
  #          gemfile: gemfiles/rails-6.1.mysql2

  #  env:
  #    BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
  #  steps:
  #  - uses: actions/checkout@v2

  #  - name: Install ruby
  #    uses: ruby/setup-ruby@v1
  #    with:
  #      ruby-version: "${{ matrix.ruby }}"

  #  - name: Bundle
  #    run: |
  #      gem install bundler:1.17.3
  #      bundle _1.17.3_ install

  #  - name: Run tests
  #    env:
  #      DATABASE_URL: mysql2://root:password@127.0.0.1:3306/test
  #      RAILS_ENV: test
  #    run: |
  #      #bundle exec rake db:test:prepare
  #      bundle exec rake


  #test_pg:
  #  runs-on: ubuntu-20.04
  #  services:
  #    postgres:
  #      image: postgres
  #      env:
  #        POSTGRES_USER: postgres
  #        POSTGRES_PASSWORD: password
  #        POSTGRES_DB: test
  #      ports: ['5432:5432']

  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      include:
  #        ### RAILS VERSION TESTING
  #        ### DONT WORRY ABOUT TESTING ALL RUBY VERSIONS. THIS IS COVERED IN THE SQLITE3 TESTS
  #        - ruby: 2.6
  #          gemfile: gemfiles/rails-3.2.pg
  #        - ruby: 2.6
  #          gemfile: gemfiles/rails-4.2.pg
  #        - ruby: 2.6
  #          gemfile: gemfiles/rails-5.0.pg
  #        - ruby: 2.6
  #          gemfile: gemfiles/rails-5.1.pg
  #        - ruby: 2.6
  #          gemfile: gemfiles/rails-5.2.pg
  #        - ruby: 2.6
  #          gemfile: gemfiles/rails-6.0.pg
  #        - ruby: 2.6
  #          gemfile: gemfiles/rails-6.1.pg

  #  env:
  #    BUNDLE_GEMFILE: "${{ matrix.gemfile }}"

  #  steps:
  #  - uses: actions/checkout@v2

  #  - name: Install ruby
  #    uses: ruby/setup-ruby@v1
  #    with:
  #      ruby-version: "${{ matrix.ruby }}"

  #  - name: Bundle
  #    run: |
  #      gem install bundler:1.17.3
  #      bundle _1.17.3_ install

  #  - name: Run tests
  #    env:
  #      DATABASE_URL: postgres://postgres:password@localhost:5432/test
  #      RAILS_ENV: test
  #    run: |
  #      #bundle exec rails db:test:prepare
  #      bundle exec rake
